"""
Django settings for admin_zone project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

load_dotenv()
email_host_user_env = os.getenv('EMAIL_HOST_USER_ENV')
email_host_password_env = os.getenv('EMAIL_HOST_PASSWORD_ENV')



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#nm&uv0jt9g_-9$bwb@dxqyk7b^@-e4)b3l+(zxu6_@=@_d73v'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  # Приложение для регистрация и авторизация пользователей
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',  # зарегистрировали приложение api
    'users.apps.UsersConfig',  # зарегистрировали приложение users
    'additions.apps.AdditionsConfig',  # зарегистрировали приложение additions
    'rest_framework',
    'djoser',  # приложение для работы с JWT
    'corsheaders',  # разрешение доступа к api
    'drf_spectacular',  # подключаем расширение для автоматической генерации документации OpenAPI
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # обработчик для разрешения доступа к api CORS
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'admin_zone.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                # добавляет в контекст шаблона объект user, он может быть двух типов: AnonymousUser, либо экземпляром модели User
                # Но самое важное — у этого объекта есть свойство is_authenticated; это свойство принимает значение True, если пользователь авторизован.
                'django.contrib.messages.context_processors.messages',
                # Найди в корне проекта папку core/, в ней - папку context_processors/,
                # там - файл year.py, а в этом файле - функцию year().
                # Словарь, который она возвращает, добавь на все страницы проекта.
                'additions.context_processors.year.year',
            ],
        },
    },
]

WSGI_APPLICATION = 'admin_zone.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'users:login'
# Это адрес, на который Django будет перенаправлять пользователей
# для авторизации. Это особенно важно при использовании декоратора
# @login_required, о котором вы узнаете в следующих уроках (интрига).
# Значение по умолчанию: '/accounts/login/'

LOGIN_REDIRECT_URL = 'users:index'
# Здесь указывается, куда перенаправить пользователя после успешной
# авторизации.
# Значение по умолчанию: '/accounts/profile/'

CSRF_TRUSTED_ORIGINS = [
    'http://127.0.0.1:8000/', 'https://*.com',
    'http://*.com', 'https://*.ru'
    ]
# https://*.com - по сути любой адрес
# это адреса с которых допустимы POST - запросы

# письма с ссылкой на востановление пароля приходит в консоль
# для учебеного проекта этого достаточно
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# настройка для почтового сервера Яндекс
# у меня заработало, но только если у пользователя почта тоже из яндекса
# EMAIL_HOST = 'smtp.yandex.ru'
# EMAIL_PORT = 465
# EMAIL_USE_TLS = False
# EMAIL_USE_SSL = True
# EMAIL_HOST_USER = 'irinademd@yandex.ru'
# EMAIL_HOST_PASSWORD = 'zqmwpwokohdhkplz'


# настройка для почтового сервера Google
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = os.environ['email_host_user_env']
EMAIL_HOST_PASSWORD = os.environ['email_host_password_env']

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER
EMAIL_ADMIN = EMAIL_HOST_USER

REST_FRAMEWORK = {
    # разрешить доступ к апи только зарегистрированным пользователям
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

    # аутентификация осуществляется с помощью JWT
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],

    # ограничение суточного количества запросов
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.AnonRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '10000/day',  # Лимит для UserRateThrottle
        'anon': '1000/day',  # Лимит для AnonRateThrottle
    },

    # добавим разбиение ответа API по страницам - пагинация
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,

    # Схема для автоматической генерации API-документации OpenAPI
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SIMPLE_JWT = {
    # Устанавливаем срок жизни токена
    'ACCESS_TOKEN_LIFETIME': timedelta(days=360),
    # В заголовке у токена будет слово носитель - Bearer, вместо слова
    # Token по умолчанию
    'AUTH_HEADER_TYPES': ('Bearer', )
}

AUTH_USER_MODEL = 'api.CustomUser'  # переопределили модель User

# Cross-Origin Resource Sharing, CORS
# (англ. «совместное использование ресурсов между разными источниками»)
CORS_ORIGIN_ALLOW_ALL = True
# начинаются с api далее любые (.) символы повторяющиеся сколько угодно раз (*)
CORS_URLS_REGEX = r'^/api/v1/.*$'

# Настройки для drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'Join-project API',  # Название API
    # Описание API
    'DESCRIPTION': 'API для управления постами, комментариями, фоловерами социальной сети.',
    'VERSION': 'v1',  # Версия API
    'SERVE_INCLUDE_SCHEMA': False  # Отключение схемы в ответах API
}
